services:
  svelte_server:
    image: "denoland/deno:alpine"
    build: 
      context: .
    environment:
      - DOTENV_KEY=${DOTENV_KEY}
      - NODE_ENV=production
    tags: 
      - "svelte_server:latest"
    ports: 
      - 3000:3000
    volumes: 
      - /data/coolify/proxy:/app/tls
  redis:
    image: redis:7.2-alpine
    ports: 
      - 3888:6379
    volumes:
      - redis_data:/redis_data

volumes:
  redis_data: