version: "3.8"

services:
  svelte_server:
    image: "denoland/deno:alpine"
    build: 
      context: .
      args:
        - DOTENV_KEY=${DOTENV_KEY}
    environment:
      - DOTENV_KEY=${DOTENV_KEY}
      - NODE_ENV=production
    ports: 
      - 3000:3000
    networks:
      - piita_network
  redis:
    image: redis:7.2-alpine
    ports: 
      - 3888:6379
    volumes:
      - redis_data:/redis_data
    networks:
      - piita_network

volumes:
  redis_data:

networks:
  piita_network:
    driver: bridge