version: "3.8"

services:
  
  svelte_server:
    env_file: ./.env.local
    image: "denoland/deno:alpine"
    build: .
    ports: 
      - 3000:3669
    networks:
      - piita_network
  redis:
    env_file: "./.env.local"
    image: redis:7.2-alpine
    ports: 
      - 3888:6379
    volumes:
      - redis_data:/redis_data
    networks:
      - piita_network

volumes:
  redis_data:

networks:
  piita_network:
    driver: bridge