services:
  svelte_server:
    build: 
      context: .
      tags: 
        - "svelte_server:latest"
    environment:
      - DOTENV_KEY=${DOTENV_KEY}
      - NODE_ENV=production
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
    ports: 
      - 3000:3000
    volumes: 
      - /data/coolify/proxy:/app/tls:ro
  redis:
    image: redislabs/rejson:latest
    ports: 
      - 3888:6379
    volumes:
      - redis_data:/redis_data

volumes:
  redis_data: