version: "3.8"

services:
  frontend:
    from: "denoland/deno:alpine"
    build: ./Dockerfile.front
    ports: 
      - 3669 3669
    networks:
      - app_network
  backend:
    from: "denoland/deno:alpine"
    build: ./Dockerfile.back
    ports: 
      - 3770:3770
    networks:
      - app_network
  redis:
    from: redis:alpine
    ports: 
      - 3888:3888
    volumes:
      - redis_data:/redis_data
    networks:
      - app_network

volumes:
  redis_data:


networks:
  app_netowrk:
    driver: bridge